# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['skippy_coach_production.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('chroma', 'chroma'),
        ('data', 'data'),
        ('logs', 'logs'),
    ],
    hiddenimports=[
        'streamlit',
        'streamlit.web',
        'streamlit.runtime',
        'streamlit.runtime.scriptrunner',
        'streamlit.runtime.state',
        'streamlit.components',
        'streamlit.elements',
        'streamlit.logger',
        'streamlit.proto',
        'streamlit.source_util',
        'streamlit.uploaded_file_manager',
        'streamlit.web.cli',
        'streamlit.web.server',
        'langchain_openai',
        'langchain_chroma',
        'langchain_core',
        'langchain_core.documents',
        'langchain_core.prompts',
        'langchain_core.callbacks',
        'langchain_core.retrievers',
        'langchain.chains.combine_documents',
        'langchain.chains',
        'langchain',
        'chromadb',
        'chromadb.api',
        'chromadb.config',
        'chromadb.db',
        'chromadb.telemetry',
        'openai',
        'tiktoken',
        'pydantic',
        'pydantic.v1',
        'numpy',
        'pandas',
        'sqlite3',
        'pathlib',
        'datetime',
        'logging',
        'json',
        're',
        'os',
        'typing',
        'dataclasses',
        'enum',
        'functools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SkippyCoach',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
